server:
  port: 8087
  
application:
   endpoints:
      ml-app:
         timeout: 10
         base-url: "https://reqres.in/api"
         get-gender: "/users"
         
spring:
   profiles:
      active: #spring.profiles.active#
   http:
      multipart:
         max-file-size: 5MB
         max-request-size: 5MB
